name: schematic_dev
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.6.24=0
  - cairo=1.14.12=h7636065_2
  - certifi=2020.6.20=py37_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - fribidi=1.0.9=h7b6447c_0
  - glib=2.65.0=h3eb4bd4_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h25d223c_0
  - harfbuzz=1.7.6=h5f0a787_1
  - icu=58.2=he6710b0_3
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libtool=2.4.6=h7b6447c_5
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pango=1.42.0=h377f3fa_0
  - pcre=8.44=he6710b0_0
  - pip=20.1.1=py37_1
  - pixman=0.40.0=h7b6447c_0
  - python=3.7.7=hcff3b4d_5
  - python-graphviz=0.8.4=py37_1
  - readline=8.0=h7b6447c_0
  - setuptools=47.3.1=py37_0
  - sqlite=3.32.3=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h0b5b093_0
  - pip:
    - attrs==19.3.0
    - cachetools==4.1.1
    - cffi==1.14.0
    - chardet==3.0.4
    - cryptography==2.9.2
    - decorator==4.4.2
    - deprecated==1.2.4
    - entrypoints==0.3
    - fastjsonschema==2.14.4
    - google-api-python-client==1.7.9
    - google-auth==1.19.1
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.4.0
    - httplib2==0.18.1
    - idna==2.10
    - importlib-metadata==1.7.0
    - inflection==0.3.1
    - isodate==0.6.0
    - jsonschema==3.2.0
    - keyring==12.0.2
    - keyrings-alt==3.1
    - networkx==2.4
    - numpy==1.19.0
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - orderedset==2.0.1
    - pandas==1.0.5
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygsheets==2.0.3.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - rdflib==4.2.2
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - secretstorage==2.3.1
    - six==1.15.0
    - synapseclient==2.1.0
    - tabletext==0.1
    - uritemplate==3.0.1
    - urllib3==1.25.9
    - wrapt==1.12.1
    - zipp==3.1.0
    - pyyaml==5.3.1
prefix: /home/xdoan/bin/home/xdoan/bin/miniconda3/envs/data_curator_env

